apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: payment-service-service
  labels:
    app: payment-service-service
spec:
  type: NodePort
  ports:
  - port: 8001
    name: payment-service-service
    targetPort: 8001
  selector:
    app: payment-service-service


apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    app: payment-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service-deployment
  template:
    metadata:
      labels:
        app: payment-service-deployment
    spec:
      containers:
      - name: housingo
        image: gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/payment-service:staging
        imagePullPolicy: Always
        env:
        - name: DB_STRING 
          value: ${{ secrets.DB_STRING }}
        - name: PORT
          value: "8000"
        - name: JWT_SECRET
          value: ${{ secrets.JWT_SECRET }}
        - name: STRIPE_KEY_LIVE
          value: ${{ secrets.STRIPE_KEY_LIVE }}
        - name: STRIPE_KEY_TEST
          value: ${{ secrets.STRIPE_KEY_TEST }}
        ports:
        - containerPort: 8001
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"